### ISSUE TITLE
🐞 [BUG]: Views and Clicks do not need signs ($ or %)

### ISSUE THREAD

**Issue by philipmuh** [Tincre/promo-dashboard#12]
Views and clicks have a $ sign, which makes no sense. They should have no units and be in natural number units.

<img width="1321" alt="Screen Shot 2023-05-22 at 1 23 25 PM" src="https://github.com/Tincre/promo-dashboard/assets/22937971/7875fc13-c619-438b-8652-cc17f262c2e6">

**Comment by thinkjrs** [comment]
This looks to be an issue with my commit 945c6ba9139e214276303efb09acedf22116a262 which "fixed" the percent sign with CTR.
