### ISSUE TITLE
🐞 [BUG] Click-through rate (CTR) needs to be displayed in %, not $

### ISSUE THREAD

**Issue by philipmuh** [Tincre/promo-dashboard#8]
**Describe the bug**
CTR is currently displayed in $. Needs to switch to %.

<img width="1406" alt="Screen Shot 2023-05-17 at 12 24 51 PM" src="https://github.com/Tincre/promo-dashboard/assets/22937971/0c72416b-2fb7-4b15-821c-bb1c5fa7f20a">

**Comment by thinkjrs** [comment]
I'm working on this now. Appears to be a typo in `src/lib/coerce.ts`, line 161.
